use thiserror::Error;
use reqwest::{Client, StatusCode};
use serde::Deserialize;
use serde_json::json;
use std::time::Duration;
use std::env;
use tokio::time::sleep;
use futures_util::StreamExt;

/// Represents an error that can occur during AI operations.
#[derive(Error, Debug)]
pub enum AiError {
    /// An error occurred during an API request.
    #[error("API Request failed: {0}")]
    Request(#[from] reqwest::Error),
    /// An environment variable was missing.
    #[error("Environment variable missing: {0}")]
    Env(#[from] std::env::VarError),
    /// An error occurred while processing the response stream.
    #[error("Stream error: {0}")]
    Stream(String),
    /// JSON parsing error
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),
}

/// Response from OpenRouter models API
#[derive(Debug, Deserialize)]
struct ModelsResponse {
    data: Vec<ModelInfo>,
}

/// Information about an AI model
#[derive(Debug, Deserialize, Clone)]
pub struct ModelInfo {
    pub id: String,
    pub name: Option<String>,
    pub description: Option<String>,
    pub context_length: Option<u32>,
    pub pricing: Option<ModelPricing>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct ModelPricing {
    pub prompt: String,
    pub completion: String,
}

/// A client for interacting with the OpenRouter AI API.
#[derive(Clone)]
pub struct AiClient {
    client: Client,
    api_key: String,
    /// The name of the model to use (e.g., "openai/gpt-4o-mini")
    pub model: String,
}

impl AiClient {
    /// Creates a new `AiClient`.
    ///
    /// # Arguments
    ///
    /// * `model` - The name of the OpenRouter model to use.
    ///
    /// # Returns
    ///
    /// A `Result` containing the `AiClient` instance or an `AiError` if the API key is missing.
    ///
    /// # Environment Variables
    ///
    /// Requires the `OPENROUTER_API_KEY` environment variable to be set.
    pub fn new(model: String) -> Result<Self, AiError> {
        let api_key = env::var("OPENROUTER_API_KEY")?;
        Ok(Self {
            client: Client::new(),
            api_key,
            model,
        })
    }

    /// Lists all available models from OpenRouter.
    ///
    /// # Returns
    ///
    /// A `Result` containing a vector of `ModelInfo` or an `AiError`.
    pub async fn list_models(&self) -> Result<Vec<ModelInfo>, AiError> {
        let url = "https://openrouter.ai/api/v1/models";
        
        let resp = self.client
            .get(url)
            .header("Authorization", format!("Bearer {}", self.api_key))
            .send()
            .await?;

        if !resp.status().is_success() {
            return Err(AiError::Stream(format!("API Error: {}", resp.status())));
        }

        let models_response: ModelsResponse = resp.json().await?;
        Ok(models_response.data)
    }

    /// Lists only free models from OpenRouter (where pricing is 0).
    ///
    /// # Returns
    ///
    /// A `Result` containing a vector of free `ModelInfo` or an `AiError`.
    pub async fn list_free_models(&self) -> Result<Vec<ModelInfo>, AiError> {
        let all_models = self.list_models().await?;
        
        let free_models: Vec<ModelInfo> = all_models
            .into_iter()
            .filter(|model| {
                if let Some(pricing) = &model.pricing {
                    pricing.prompt == "0" && pricing.completion == "0"
                } else {
                    false
                }
            })
            .collect();

        Ok(free_models)
    }

    /// Streams content generated by the OpenRouter API in response to a prompt.
    ///
    /// This function is suitable for interactive applications where responses can be displayed incrementally.
    /// It handles retries for rate limiting (HTTP 429 errors).
    ///
    /// # Arguments
    ///
    /// * `prompt` - The user's input prompt.
    /// * `system_instruction` - Instructions for the AI model to guide its behavior or persona.
    ///
    /// # Returns
    ///
    /// A `Result` containing a stream of strings (each representing a part of the generated text)
    /// or an `AiError` if an error occurs during the request or stream processing.
    pub async fn stream_completion(
        &self,
        prompt: &str,
        system_instruction: &str,
    ) -> Result<impl futures_util::Stream<Item = Result<String, AiError>>, AiError> {
        let url = "https://openrouter.ai/api/v1/chat/completions";

        let body = json!({
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": system_instruction
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "stream": true,
            "temperature": 0.7,
            "max_tokens": 8192
        });

        // Retry Loop for 429
        let mut attempts = 0;
        let max_retries = 3;
        
        loop {
            let resp = self.client
                .post(url)
                .header("Authorization", format!("Bearer {}", self.api_key))
                .header("HTTP-Referer", "https://github.com/yourusername/gogit")
                .header("X-Title", "gogit")
                .json(&body)
                .send()
                .await?;

            if resp.status() == StatusCode::TOO_MANY_REQUESTS {
                if attempts >= max_retries {
                    return Err(AiError::Stream("Rate limit exceeded after retries".to_string()));
                }
                attempts += 1;
                eprintln!("\n[Rate Limit] Waiting 10s before retry ({}/{})...", attempts, max_retries);
                sleep(Duration::from_secs(10)).await;
                continue;
            }

            if !resp.status().is_success() {
                let status = resp.status();
                let error_text = resp.text().await.unwrap_or_default();
                return Err(AiError::Stream(format!("API Error {}: {}", status, error_text)));
            }

            let stream = resp.bytes_stream();
            let mut stream = Box::pin(stream);

            return Ok(async_stream::try_stream! {
                while let Some(item) = stream.next().await {
                    let bytes = item?;
                    let chunk_str = String::from_utf8_lossy(&bytes);
                    
                    // OpenRouter uses SSE format: "data: {...}\n\n"
                    for line in chunk_str.lines() {
                        if line.starts_with("data: ") {
                            let json_str = line.strip_prefix("data: ").unwrap();
                            
                            if json_str == "[DONE]" {
                                break;
                            }
                            
                            if let Ok(json) = serde_json::from_str::<serde_json::Value>(json_str) {
                                if let Some(delta) = json["choices"][0]["delta"]["content"].as_str() {
                                    yield delta.to_string();
                                }
                            }
                        }
                    }
                }
            });
        }
    }

    /// Generates a text completion from the OpenRouter API.
    ///
    /// This function makes a single request and returns the entire generated text.
    /// It includes retry logic for rate limiting (HTTP 429 errors).
    ///
    /// # Arguments
    ///
    /// * `prompt` - The user's input prompt.
    /// * `system_instruction` - Instructions for the AI model to guide its behavior or persona.
    ///
    /// # Returns
    ///
    /// A `Result` containing the generated text string or an `AiError` if an error occurs.
    pub async fn generate_text(&self, prompt: &str, system_instruction: &str) -> Result<String, AiError> {
        let url = "https://openrouter.ai/api/v1/chat/completions";

        let body = json!({
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": system_instruction
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.7,
            "max_tokens": 8192
        });

        // Retry logic for 429
        let mut attempts = 0;
        loop {
            let resp = self.client
                .post(url)
                .header("Authorization", format!("Bearer {}", self.api_key))
                .header("HTTP-Referer", "https://github.com/yourusername/gogit")
                .header("X-Title", "gogit")
                .json(&body)
                .send()
                .await?;
                
            if resp.status() == StatusCode::TOO_MANY_REQUESTS {
                if attempts >= 3 {
                    return Err(AiError::Stream("Rate limit exceeded".to_string()));
                }
                attempts += 1;
                sleep(Duration::from_secs(5)).await;
                continue;
            }

            let json: serde_json::Value = resp.json().await?;
            
            if let Some(text) = json["choices"][0]["message"]["content"].as_str() {
                return Ok(text.to_string());
            } else if let Some(error) = json.get("error") {
                let msg = error["message"].as_str().unwrap_or("Unknown API error");
                return Err(AiError::Stream(format!("OpenRouter API Error: {}", msg)));
            } else {
                return Err(AiError::Stream(format!("Unexpected JSON response: {}", json)));
            }
        }
    }

    /// Generates a concise summary of code changes from a git diff.
    ///
    /// For very large diffs (over 500,000 characters), it splits the diff into chunks
    /// and summarizes each chunk individually to avoid exceeding token limits or rate limits.
    ///
    /// # Arguments
    ///
    /// * `diff` - A string slice containing the git diff output.
    ///
    /// # Returns
    ///
    /// A `Result` containing the summarized changes as a string or an `AiError`.
    pub async fn smart_diff_summary(&self, diff: &str) -> Result<String, AiError> {
        // Most models have large context windows, but we still want to avoid rate limits
        if diff.len() < 500_000 {
            return Ok(diff.to_string());
        }
        let parts: Vec<&str> = diff.split("diff --git").collect();
        let mut summaries = Vec::new();
        for part in parts {
            if part.trim().is_empty() { continue; }
            let chunk = format!("diff --git{}", part);
            let summary = self.generate_text(
                &format!("Summarize the code changes in this git diff chunk:\n\n{}", chunk),
                "You are a code summarizer. Output a concise summary of changes."
            ).await?;
            summaries.push(summary);
        }
        Ok(summaries.join("\n\n"))
    }

    /// Translates a natural language description into a git command.
    ///
    /// # Arguments
    ///
    /// * `description` - A natural language description of the desired git command.
    ///
    /// # Returns
    ///
    /// A `Result` containing the generated git command as a string or an `AiError`.
    pub async fn generate_git_command(&self, description: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Translate this natural language request into a valid git command:\n\n\"{}\"\n\nOutput ONLY the command itself, no explanation, no backticks. Example: git log --author=\"John\"", description),
            "You are a Git expert. You translate natural language descriptions into precise git commands."
        ).await
    }

    /// Suggests a git branch name based on a task description.
    ///
    /// Follows conventions like kebab-case and common prefixes (feat/, fix/, chore/).
    ///
    /// # Arguments
    ///
    /// * `description` - A description of the task or feature.
    ///
    /// # Returns
    ///
    /// A `Result` containing the suggested branch name as a string or an `AiError`.
    pub async fn suggest_branch_name(&self, description: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Suggest a concise and descriptive git branch name for the following task:\n\n\"{}\"\n\nRules:\n- Use kebab-case.\n- Include a prefix like feat/, fix/, chore/, or docs/ if appropriate.\n- Output ONLY the branch name, no explanation, no backticks.", description),
            "You are a Git expert. You suggest clean and standard branch names based on task descriptions."
        ).await
    }

    /// Resolves merge conflicts in a given file content.
    ///
    /// Removes conflict markers and attempts to preserve the logic from both sides of the conflict.
    ///
    /// # Arguments
    ///
    /// * `file_content` - The content of the file containing merge conflicts.
    /// * `file_name` - The name of the file.
    ///
    /// # Returns
    ///
    /// A `Result` containing the resolved file content as a string or an `AiError`.
    pub async fn resolve_conflicts(&self, file_content: &str, file_name: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Resolve the merge conflicts in the following file: {}\n\nContent:\n{}\n\nRules:\n- Maintain the intended logic from both sides where possible.\n- Remove all conflict markers (<<<<<<<, =======, >>>>>>>).\n- Output ONLY the resolved file content, no explanation, no backticks.", file_name, file_content),
            "You are a Senior Software Engineer. You resolve merge conflicts precisely, ensuring code integrity and following project conventions."
        ).await
    }

    /// Generates release notes in Markdown format based on a list of commits.
    ///
    /// Categorizes changes into New Features, Bug Fixes, Security, and Internal Changes.
    ///
    /// # Arguments
    ///
    /// * `commits` - A string containing the commit messages.
    ///
    /// # Returns
    ///
    /// A `Result` containing the generated release notes as a Markdown string or an `AiError`.
    pub async fn generate_release_notes(&self, commits: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Generate a professional and concise RELEASE_NOTES.md content based on these commits:\n\n{}\n\nStructure:\n- # [Version/Date]\n- ## 🚀 New Features\n- ## 🛠️ Bug Fixes\n- ## 🔒 Security\n- ## 📦 Internal Changes\n\n- Focus on the impact and value for stakeholders.\n- Output ONLY the Markdown content, no extra explanation.", commits),
            "You are a Project Manager and Senior Engineer. You write clear, impactful, and categorized release notes from raw commit logs."
        ).await
    }

    pub async fn answer_repo_question(&self, question: &str, files: &str, context: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Question about the repository:\n\"{}\"\n\nProject Structure:\n{}\n\nRelevant Context/File Contents:\n{}\n\nInstructions:\n- Answer the question accurately based on the provided files and structure.\n- Explain 'where things are' and 'how things work'.\n- Be concise and helpful for a new developer onboarding.", question, files, context),
            "You are a Senior Architect. You act as a technical guide for the codebase, helping developers navigate and understand the repository."
        ).await
    }

    pub async fn analyze_branch_staleness(&self, branch_info: &str) -> Result<String, AiError> {
        self.generate_text(
            &format!("Analyze these Git branches for staleness/redundancy:\n\n{}\n\nInstructions:\n- Identify which branches are safe to delete.\n- A branch is safe if its changes are likely already in the base branch or if it was a temporary fix.\n- Be conservative but helpful.\n- Output a clear, bulleted list with 'Safe to Delete' or 'Keep' for each branch, with a one-sentence reason.", branch_info),
            "You are a DevOps Engineer specializing in repository maintenance. You help teams keep their branches tidy and secure."
        ).await
    }
}
